#!/usr/bin/env bash
# Writes a Bash script that loops from 1 to 10 and: displays bad luck for 4th loop, good luck for the 8th loop, and Best School for the others.

count=1

while [ $count -lt 11 ]; do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
