#!/usr/bin/env bash
# Writes numbers from 1 to 20 and: displays 4 and then bad luck from china, displays 9 then bad luck from japan, displays 14 then bad luck from Italy.

count=1

while [ $count -lt 21 ]; do
	echo $count
	case "$count" in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	count=$((count + 1))
done
