#!/usr/bin/env bash
# Displays time for 12 hours and 59 minutes: displays hours from 0 to 12, displays minutes from 1 to 59.

minutes=1
hours=0

while [ $hours -lt 13 ]; do
	echo Hour: $hours
	while [ $minutes -lt 60 ]; do
		echo $minutes
		minutes=$((minutes += 1))
	done
	minutes=$((minutes = 1))
	hours=$((hours += 1))

done

