#!/usr/bin/env bash
# writes script that gives info about the school file.

if [[ -e school ]]
	then
		echo "school file exist"
	if [[ -s school ]]
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [[ -f school ]]
	echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
