#!/usr/bin/env bash
# writes script that gives info about the school file.

found=0
for school in /root; do
	if [ "$file" == "school" ]
	then
		found=$((found = 1))
	echo "school file exist"
	if [ -s "$file" ]
		then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ]
		then
		echo "school is a regular file"
	fi
	fi
done

if [ $found -eq 0 ]
	then
	echo "school file does not exist"
fi
